version: "3"
services:
  gochanneltest:
    image: golang:1.21
    restart: unless-stopped
    volumes:
      - .:/app
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /app
    command: go test ./pubsub/gochannel -run ^TestSubscriber_race_condition_when_closing$ -v
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "1"
    #       # memory: 50M
    #     reservations:
    #       cpus: "1"
    #       # memory: 20M
